# Generated by Django 5.2.4 on 2026-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_course_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
