# Generated by Django 5.2.4 on 2026-03-22 15:49

import resources.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resource/', validators=[resources.validators.validate_file_size, resources.validators.validate_file_type]),
        ),
    ]
