# Generated by Django 5.2.4 on 2026-03-22 16:48

import resources.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resource/', validators=[resources.validators.validate_file_size, resources.validators.validate_file_type]),
        ),
    ]
