# Generated by Django 5.2.4 on 2026-03-24 00:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_cloudinary_url_alter_resource_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='cloudinary_url',
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
